### ISSUE TITLE
rarefyBarcodes maxpoints dtype incompatibility

### ISSUE THREAD

**Issue by khdcrawford** [jbloomlab/dms_variants#61]
The default value for `maxpoints` in the `barcodes.rarefyBarcodes` function is the float `10000.0`. However, the dtype is specified as `int` and this dtype incompatibility makes the function break if there are more than 10000 barcodes. 

I think this can be fixed just by changing the default `maxpoints` value to the int `10000`. I can do this and submit a PR if that'd be best?

**Comment by jbloom** [comment]
That sounds great, and thanks for finding problem! Also add to `CHANGELOG` and increment version number at the last digit in `__init__.py`.

**Comment by khdcrawford** [comment]
For future information, it looks like Python interprets scientific notation as floats (and I dropped a 0 in my original post), so the default was actually set as `1e5`. I've changed it to `100000` and have incremented the `CHANGELOG` and `__init__.py`. This is fixed in PR #62
