### ISSUE TITLE
extra_cols in 

### ISSUE THREAD

**Issue by ajgreaney** [jbloomlab/dms_variants#65]
@jbloom I am now using dms_variants version `0.8.8`.
I am trying to initialize the CodonVariantTable with `dms_variants.codonvarianttable.CodonVariantTable.from_variant_count_df `. I know the `variantfile` has the 'allowed_mutant' `extra_cols` that I'm trying to include (see top of first image below). But when I try to initialize the CodonVariantTable (bottom half of image below):

![Screen Shot 2021-05-17 at 4 54 35 PM](https://user-images.githubusercontent.com/28786335/118570920-eb116b80-b731-11eb-958c-18d356e74515.png)

I get the error shown here:

![Screen Shot 2021-05-17 at 4 54 53 PM](https://user-images.githubusercontent.com/28786335/118570983-07ada380-b732-11eb-9d98-ac19eafd8ecc.png)

**Comment by jbloom** [comment]
@ajgreaney, should be fixed in version 0.8.9.
