### ISSUE TITLE
Barcodes must match case found in sequencing files to be counted

### ISSUE THREAD

**Issue by caelanradford** [jbloomlab/dms_variants#67]
This is a minor issue, but may come up if people try to add barcodes of secondary targets as standards. If you manually add barcodes to the codon variant table (for example, adding barcodes of VSVG pseodytyped viruses to be spiked in as standards), then you must match the case of the barcodes you put in to the case the barcodes will be read in from the barcode sequencing files (as in, both need to be uppercase). Not matching the case will result in none of the variants with those barcodes being counted as valid. If one is not aware of this, it might make it appear as though the barcodes of the standards are not present or not input properly.

**Comment by jbloom** [comment]
@caelanradford this is not a sufficiently detailed issue for me to do anything with it. If you want changes, you need to give some example of what you are actually doing in the code to add these, etc. Please indicate how this is being done.

**Comment by jbloom** [comment]
@caelanradford, can you either convert this to a minimal working example or close the issue if you are not going to do so.
